services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: AGD
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
