name: 02 - Workflow Filtro

on:
    push:
        branches:
            - master

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Exibir mensagem de sucesso
              run: echo "Workflow Filtro executado com sucesso!"