name: Continuos Delivery

on:
  push:
    branches:
      - master


jobs:
  build:
        runs-on: 'ubuntu-latest'
        
        steps:

        - name: Checkout of code
          uses: actions/checkout@v4
            
        - name: Install of .NET 9
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.0.x'

        - name: Restore dependencies
          run: dotnet restore

        - name: Build of application
          run: dotnet build

        - name: Clean of application
          run: dotnet clean
              
        - name: Message of successful build
          run: echo "Código buildado e limpado com sucesso!"
          
        - uses: actions/checkout@v2
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
    
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            registry: https://index.docker.io/v1/
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: push container image to registry
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/agdapi:latest
            file: ./Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-prod.outputs.web-url }}

    steps:
    - name: Deploy to azure web app
      id: deploy-to-web--app
      uses: azure/webapps-deploy@v2
      with:
        app-name: "agdapi"
        slot-name: "production"
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        images: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/agdapi
